version: '3.9'
services:
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "9080:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      URLS_PRIMARY_NAME: 'keycloak'
      URLS: "[
        {url: 'doc/project-test', name: 'project-test'},
        {url: 'doc/graphql-engine.yaml', name: 'graphql-engine'},
        {url: 'doc/keycloak.yaml', name: 'keycloak'}
      ]"